///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  static const String textImage = 'assets/images/textImage.png';
  static const String splashButtom = 'assets/images/splashButtom.png';
  static const String unseenPassword = 'assets/images/unseenPassword.png';
  static const String seenPassword = 'assets/images/seenPassword.png';
  static const String google = 'assets/images/google.png';
  static const String facebook = 'assets/images/facebook.png';
  static const String back = 'assets/images/back.png';
  static const String editProfile = 'assets/images/edit_profile.png';

  static const String imagesIcUser = 'assets/images/ic_user.png';
  static const String arrowLeft = 'assets/images/arrowLeft.png';
  static const String click = 'assets/images/click.png';
  static const String msg = 'assets/images/msg.png';
  static const String phone = 'assets/images/phone.png';
  static const String delete = 'assets/images/delete.png';
  static const String office = 'assets/images/office.png';
  static const String edit = 'assets/images/edit.png';
  static const String house = 'assets/images/house.png';
  static const String imagesIcLine = 'assets/images/ic_line.png';
  static const String cameraPng = 'assets/images/camera.png';
  static const String upload = 'assets/images/Upload_Image.png';
  static const String editText = 'assets/images/edit_text.png';
  static const String dropDown = 'assets/images/dropDown.png';



}
