///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  static const String textImage = 'assets/images/textImage.png';
  static const String splashButtom = 'assets/images/splashButtom.png';
  static const String unseenPassword = 'assets/images/unseenPassword.png';
  static const String seenPassword = 'assets/images/seenPassword.png';
  static const String google = 'assets/images/google.png';
  static const String facebook = 'assets/images/facebook.png';
  static const String back = 'assets/images/back.png';
  static const String editProfile = 'assets/images/edit_profile.png';

  static const String imagesIcUser = 'assets/images/ic_user.png';
  static const String arrowLeft = 'assets/images/arrowLeft.png';
  static const String click = 'assets/images/click.png';
  static const String msg = 'assets/images/msg.png';
  static const String phone = 'assets/images/phone.png';
  static const String delete = 'assets/images/delete.png';
  static const String office = 'assets/images/office.png';
  static const String edit = 'assets/images/edit.png';
  static const String house = 'assets/images/house.png';
  static const String imagesIcLine = 'assets/images/ic_line.png';
  static const String cameraPng = 'assets/images/camera.png';
  static const String upload = 'assets/images/Upload_Image.png';
  static const String editText = 'assets/images/edit_text.png';
  static const String dropDown = 'assets/images/dropDown.png';
  static const String navBar = 'assets/images/nav_bar.png';

  static const String homeIconUl = 'assets/images/home_icon_ul.svg';
  static const String homeIconSl = 'assets/images/home_icon_sl.svg';

  static const String bookingIconUl = 'assets/images/calender_icon_ul.svg';
  static const String bookingIconSl = 'assets/images/calender_icon_sl.svg';

  static const String cartIconUl = 'assets/images/bag_icon_ul.svg';
  static const String cartIconSl = 'assets/images/bag_icon_sl.svg';

  static const String profileIconUl = 'assets/images/profile_icon_ul.svg';
  static const String profileIconSl = 'assets/images/profile_icon_sl.svg';

  static const String scanIcon = 'assets/images/scan_icon.svg';

  // home_scrrens
  static const String dummyBanner = 'assets/dummy_images/home_banner.png';
  static const String p1 = 'assets/dummy_images/p1.png';
  static const String p2 = 'assets/dummy_images/p2.png';
  static const String p3 = 'assets/dummy_images/p3.png';
  static const String p4 = 'assets/dummy_images/p4.png';
  static const String p5 = 'assets/dummy_images/p5.png';
  static const String p6 = 'assets/dummy_images/p6.png';
  static const String notificationIcon = 'assets/images/ic_bell.svg';
  static const String favouriteIcon = 'assets/images/ic_heart.svg';
  static const String appNameVertical = 'assets/images/app_logo_vertical.png';
  static const String appLogo = 'assets/images/app_logo.png';
  static const String searchIcon = 'assets/images/ic_search.svg';
  static const String trashIcon = 'assets/images/ic_delete.svg';
}
